name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        nixpkgs_version: ["master"]
    env:
      NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/${{ matrix.nixpgs_version }}.tar.gz"
    steps:
    - uses: cachix/install-nix-action@v8
    - uses: actions/checkout@v1
    - uses: cachix/cachix-action@v6
      with:
        name: test container deployment
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: ./run
